### ISSUE TITLE
[BUG]: Our current cmake config potentially filters all available architectures

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#402] opened 2023-09-05 07:49 UTC
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

CUB

### Describe the bug

Currently we are filtering the available `CMAKE_CUDA_ARCHITECTURES` in cub/cmake/CubCudaConfig.cmake as well as thrust/cmake/ThrustCudaConfig.cmake

If the user only provided a single architecture e.g "90" then the test run will fail with:
```
CMake Error in cub/test/CMakeLists.txt:
  CUDA_ARCHITECTURES is empty for target
```

We should ensure that when filtering the provided `CMAKE_CUDA_ARCHITECTURES` we do not remove all available ones but at least fall back to a proper default architecture that is also supported on that target.

### How to Reproduce

Run one of our ci scripts with a single architecture that is in that list, e.g.
```bash
./ci/test_cub.sh gcc 17 "90"
```

### Expected behavior

We should still be able to build and run all tests even if we fall back to a lower architecture

**Comment by jrhemstad** [comment] 2023-09-05 14:40
I'm going to mark this as a duplicate of https://github.com/NVIDIA/cccl/issues/219.

I want to get rid of or modify this filtering to apply on a per-target basis instead of doing it globally. Falling back to a different architecture than what was specified would be too astonishing imo.

**Closed by jrhemstad** 2023-09-05 14:40 UTC
Labels: nvbug, thrust, cub, bug, infrastructure
