### ISSUE TITLE
mdarray multi-dimensional owning abstraction

### ISSUE THREAD

**Issue by pciolkosz** [NVIDIA/cccl#2888] opened 2024-11-19 19:04 UTC

**Comment by fbusato** [comment] 2024-11-19 19:33
it is a duplicate of https://github.com/NVIDIA/cccl/issues/2474

**Comment by jrhemstad** [comment] 2024-12-04 18:00
Closing in favor of https://github.com/NVIDIA/cccl/issues/2474.

**Closed by jrhemstad** 2024-12-04 18:00 UTC
