### ISSUE TITLE
Make libcu++ matrix green

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#108] opened 2023-06-21 15:56 UTC

**Comment by senior-zero** [comment] 2023-06-22 11:16
@miscco the CUB [build](https://github.com/NVIDIA/cccl/actions/runs/5341249781/jobs/9681890818) against ctk 11.1 / gcc 7 is broken and I think it's mainly due to libcu++:

```cpp
include/cuda/std/detail/libcxx/include/__functional/binary_function.h(37): error #738: a class-qualified name is required
```

**Comment by miscco** [comment] 2023-06-22 15:22
thanks, @senior-zero I have merged a fix ;)

**Comment by senior-zero** [comment] 2023-06-23 00:09
@miscco another CUB [failure](https://github.com/NVIDIA/cccl/actions/runs/5351418728/jobs/9705214137) that seems to be caused by libcu++ (CTK 11.1/ llvm 9):

```
include/cuda/std/detail/libcxx/include/__type_traits/../__type_traits/common_type.h(115): here
            [ 172 instantiation contexts not shown ]
            instantiation of class "cuda::std::__4::common_type<_Tp, _Up> [with _Tp=cuda::std::__4::__decay_t<long long>, _Up=cuda::std::__4::__decay_t<long long>]" 
/__w/cccl/cccl/libcudacxx/lib/cmake/libcudacxx/../../../include/cuda/std/detail/libcxx/include/__type_traits/../__type_traits/common_type.h(114): here
            instantiation of class "cuda::std::__4::common_type<_Tp, _Up> [with _Tp=long long, _Up=long long]" 
/__w/cccl/cccl/libcudacxx/lib/cmake/libcudacxx/../../../include/cuda/std/detail/libcxx/include/chrono(912): here
            instantiation of class "cuda::std::__4::common_type<cuda::std::__4::chrono::duration<_Rep1, _Period1>, cuda::std::__4::chrono::duration<_Rep2, _Period2>> [with _Rep1=long long, _Period1=cuda::std::__4::nano, _Rep2=long long, _Period2=cuda::std::__4::nano]" 
/__w/cccl/cccl/libcudacxx/lib/cmake/libcudacxx/../../../include/cuda/std/detail/libcxx/include/__type_traits/../__type_traits/common_type.h(107): here
            instantiation of class "cuda::std::__4::common_type<_Tp> [with _Tp=cuda::std::__4::chrono::duration<long long, cuda::std::__4::nano>]" 
/__w/cccl/cccl/libcudacxx/lib/cmake/libcudacxx/../../../include/cuda/std/detail/libcxx/include/chrono(1140): here
            instantiation of class "cuda::std::__4::chrono::duration<_Rep, _Period> [with _Rep=long long, _Period=cuda::std::__4::nano]" 
/__w/cccl/cccl/libcudacxx/lib/cmake/libcudacxx/../../../include/cuda/std/detail/libcxx/include/chrono(1613): here
```

**Comment by miscco** [comment] 2023-07-03 10:16
We are green

**Closed by miscco** 2023-07-03 10:16 UTC
